server:
  port: 8765
zuul:
  ignoredServices: '*'
  routes:
    config:
      path: /config/default
      serviceId: config-service
    categories:
      path: /categories/**
      serviceId: category-service
    vendors:
      path: /vendors/**
      serviceId: vendor-service
eureka:
  client:
    service-url:
      defaultZone: http://naming:8761/eureka/
    registerWithEureka: true
    fetchRegistry: true
  instance:
    prefer-ip-address: true

spring:
  application:
    name: zuul-gateway


logging:
  level:
    ROOT: INFO
    org.springframework.web: DEBUG