server:
  port: 8765
zuul:
  ignoredServices: '*'
  routes:
    config:
      path: /config/**
      serviceId: config-service
    products:
      path: /products/**
      serviceId: product-service
    categories:
      path: /categories/**
      serviceId: category-service
    vendors:
      path: /vendors/**
      serviceId: vendor-service
    user:
      path: /user/**
      serviceId: user-service
  # don't allow production configs to be accessed via gateway
  ignored-patterns: /config/**/prod
eureka:
  client:
    service-url:
#      FIXME RESORT BACK!
#      defaultZone: http://naming:8761/eureka/
      defaultZone: http://localhost:8761/eureka
    registerWithEureka: true
    fetchRegistry: true
  instance:
    prefer-ip-address: true

spring:
  application:
    name: zuul-gateway


logging:
  level:
    ROOT: INFO
    org.springframework.web: DEBUG